
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: numbers_summarizer_backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: numbers_summarizer_frontend
    ports:
      - "5174:80"
    environment:
      - REACT_APP_API_URL=http://backend:8081
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge